export const EconomyConfig = {
    // Normal items available for random rotation
    buyPoolNormal: {
        "minecraft:bread": 2500,
        "minecraft:cooked_beef": 5000,
        "minecraft:torch": 500,
        "minecraft:arrow": 1000,
        "minecraft:apple": 1500,
        "minecraft:iron_ingot": 8000,
        "minecraft:gold_ingot": 12000,
        "minecraft:coal": 2000,
        "minecraft:redstone": 3000,
        "minecraft:lapis_lazuli": 4000,
        "minecraft:oak_log": 3500,
        "minecraft:cobblestone": 200,
        "minecraft:dirt": 100,
        "minecraft:sand": 200,
        "minecraft:glass": 800,
        "minecraft:string": 1000,
        "minecraft:leather": 2000,
        "minecraft:feather": 1000,
        "minecraft:slime_ball": 5000,
        "minecraft:ender_pearl": 15000,
        "minecraft:blaze_rod": 20000,
        "minecraft:gunpowder": 3000,
        "minecraft:experience_bottle": 10000,
        "minecraft:name_tag": 50000,
        "minecraft:saddle": 75000,
        "minecraft:obsidian": 8000,
        "minecraft:quartz": 3000,
        "minecraft:glowstone_dust": 2500,
        "minecraft:magma_block": 4000,
        "minecraft:soul_sand": 3000,
        "minecraft:nether_wart": 5000,
        "minecraft:bone": 1000,
        "minecraft:spider_eye": 2000,
        "minecraft:rotten_flesh": 500,
        "minecraft:sweet_berries": 1000,
        "minecraft:carrot": 2000,
        "minecraft:potato": 2000,
        "minecraft:wheat": 2000,
        "minecraft:sugar_cane": 3000,
        "minecraft:bamboo": 1000
    },
    // OP items with insane prices
    buyPoolOP: {
        "minecraft:enchanted_golden_apple": 1000000,
        "minecraft:elytra": 5000000,
        "minecraft:nether_star": 2000000,
        "minecraft:totem_of_undying": 500000,
        "minecraft:beacon": 3000000,
        "minecraft:shulker_box": 750000,
        "minecraft:diamond_block": 500000,
        "minecraft:netherite_ingot": 1200000,
        "minecraft:dragon_breath": 800000,
        "minecraft:heart_of_the_sea": 600000
    },
    sellPrices: {
        // Pertanian & Alam (Farming & Nature) - NERFED
        "minecraft:wheat": 15,
        "minecraft:potato": 10,
        "minecraft:carrot": 10,
        "minecraft:beetroot": 15,
        "minecraft:melon_slice": 8,
        "minecraft:pumpkin": 20,
        "minecraft:sugar_cane": 10,
        "minecraft:bamboo": 5,
        "minecraft:apple": 50,
        "minecraft:sweet_berries": 5,
        "minecraft:glow_berries": 15,
        "minecraft:kelp": 5,
        "minecraft:cocoa_beans": 25,
        "minecraft:cactus": 10,
        "minecraft:brown_mushroom": 20,
        "minecraft:red_mushroom": 20,
        "minecraft:nether_wart": 100,
        "minecraft:chorus_fruit": 250,
        "minecraft:oak_log": 30,
        "minecraft:spruce_log": 30,
        "minecraft:birch_log": 30,
        "minecraft:jungle_log": 30,
        "minecraft:acacia_log": 30,
        "minecraft:dark_oak_log": 30,
        "minecraft:cherry_log": 50,
        "minecraft:mangrove_log": 50,

        // Hasil Tambang (Ores & Mining) - NERFED EMERALD/IRON
        "minecraft:coal": 20,
        "minecraft:raw_iron": 30,
        "minecraft:iron_ingot": 50,
        "minecraft:raw_copper": 15,
        "minecraft:copper_ingot": 25,
        "minecraft:raw_gold": 250,
        "minecraft:gold_ingot": 400,
        "minecraft:lapis_lazuli": 20,
        "minecraft:redstone": 15,
        "minecraft:diamond": 5000, // Reduced from 50k to 5k
        "minecraft:emerald": 100,  // SEVERELY NERFED (easily farmable from villagers)
        "minecraft:amethyst_shard": 150,
        "minecraft:quartz": 30,
        "minecraft:netherite_scrap": 50000,
        "minecraft:netherite_ingot": 250000,
        "minecraft:obsidian": 200,
        "minecraft:crying_obsidian": 400,

        // Mob Drops (Biasa & Langka) - NERFED BASE DROPS
        "minecraft:rotten_flesh": 2,
        "minecraft:bone": 5,
        "minecraft:string": 5,
        "minecraft:spider_eye": 10,
        "minecraft:gunpowder": 15,
        "minecraft:ender_pearl": 200,
        "minecraft:blaze_rod": 400,
        "minecraft:ghast_tear": 1000,
        "minecraft:magma_cream": 50,
        "minecraft:slime_ball": 40,
        "minecraft:phantom_membrane": 250,
        "minecraft:shulker_shell": 3000,
        "minecraft:wither_skeleton_skull": 15000,
        "minecraft:nether_star": 250000,
        "minecraft:dragon_egg": 1000000,
        "minecraft:leather": 15,
        "minecraft:feather": 5,
        "minecraft:rabbit_hide": 10,
        "minecraft:rabbit_foot": 150,
        "minecraft:scute": 500,
        "minecraft:turtle_helmet": 5000,
        "minecraft:nautilus_shell": 2000,
        "minecraft:heart_of_the_sea": 25000,
        "minecraft:sponge": 5000,

        // Bahan Bangunan & Alam (Blocks) - SEVERELY NERFED
        "minecraft:dirt": 1,
        "minecraft:cobblestone": 2,
        "minecraft:stone": 5,
        "minecraft:sand": 2,
        "minecraft:gravel": 2,
        "minecraft:glass": 10,
        "minecraft:clay_ball": 15,
        "minecraft:brick": 25,
        "minecraft:snowball": 1,
        "minecraft:ice": 20,
        "minecraft:packed_ice": 60,
        "minecraft:blue_ice": 250,
        "minecraft:prismarine_shard": 50,
        "minecraft:prismarine_crystals": 75,
        "minecraft:glowstone_dust": 15,
        "minecraft:magma_block": 30,
        "minecraft:soul_sand": 10,
        "minecraft:soul_soil": 10,
        "minecraft:basalt": 5,
        "minecraft:blackstone": 5,

        // Item Makanan Olahan & Lainnya (Food & Misc)
        "minecraft:cooked_porkchop": 40,
        "minecraft:cooked_mutton": 40,
        "minecraft:cooked_chicken": 30,
        "minecraft:cooked_rabbit": 50,
        "minecraft:cooked_cod": 20,
        "minecraft:cooked_salmon": 30,
        "minecraft:golden_apple": 2500,
        "minecraft:enchanted_golden_apple": 150000,
        "minecraft:golden_carrot": 150,
        "minecraft:glistering_melon_slice": 150,
        "minecraft:honeycomb": 50,
        "minecraft:honey_bottle": 60,
        "minecraft:totem_of_undying": 10000, // Easily farmable from raids, severely nerfed
        "minecraft:experience_bottle": 100,
        "minecraft:name_tag": 500,
        "minecraft:saddle": 500,
        "minecraft:iron_horse_armor": 400,
        "minecraft:golden_horse_armor": 800,
        "minecraft:diamond_horse_armor": 5000,
        "minecraft:bell": 1000,
        "minecraft:lead": 50,
        "minecraft:compass": 200,
        "minecraft:recovery_compass": 5000,
        "minecraft:echo_shard": 1500
    }
};
